export const COUNTRIES = [
  { name: "India", dial: "+91" },
  { name: "United States", dial: "+1" },
  { name: "United Kingdom", dial: "+44" },
  { name: "Canada", dial: "+1" },
  { name: "Australia", dial: "+61" },
  { name: "Germany", dial: "+49" },
  { name: "France", dial: "+33" },
  { name: "Spain", dial: "+34" },
  { name: "Italy", dial: "+39" },
  { name: "Netherlands", dial: "+31" },
  { name: "Ireland", dial: "+353" },
  { name: "Sweden", dial: "+46" },
  { name: "Norway", dial: "+47" },
  { name: "Denmark", dial: "+45" },
  { name: "Switzerland", dial: "+41" },
  { name: "Belgium", dial: "+32" },
  { name: "Portugal", dial: "+351" },
  { name: "Poland", dial: "+48" },
  { name: "Austria", dial: "+43" },
  { name: "United Arab Emirates", dial: "+971" },
  { name: "Saudi Arabia", dial: "+966" },
  { name: "Singapore", dial: "+65" },
  { name: "Hong Kong", dial: "+852" },
  { name: "Japan", dial: "+81" },
  { name: "South Korea", dial: "+82" },
  { name: "New Zealand", dial: "+64" },
  { name: "South Africa", dial: "+27" },
  { name: "Brazil", dial: "+55" },
  { name: "Mexico", dial: "+52" },
  { name: "Argentina", dial: "+54" },
  { name: "Israel", dial: "+972" },
  { name: "Philippines", dial: "+63" },
  { name: "Malaysia", dial: "+60" },
  { name: "Indonesia", dial: "+62" },
  { name: "Thailand", dial: "+66" },
  { name: "Vietnam", dial: "+84" },
  { name: "Bangladesh", dial: "+880" },
  { name: "Nigeria", dial: "+234" },
  { name: "Egypt", dial: "+20" },
  { name: "Russia", dial: "+7" },
];
